### PR TITLE
Fix issue #182 (exception in FandomParser), update presets

### LINKED ISSUE #182: FandomParser throws ArgumentNullException
Stack trace:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: obj
   at System.OrdinalComparer.GetHashCode(String obj)
   at FandomParser.WikiText.WikiTextTableEntryComparer.GetHashCode(WikiTextTableEntry obj) in C:\Users\Agmas\source\repos\anno-designer\FandomParser\FandomParser\WikiText\WikiTextTableEntryComparer.cs:line 45
   at System.Linq.Set`1.InternalGetHashCode(TElement value)
   at System.Linq.Set`1.Find(TElement value, Boolean add)
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at FandomParser.WikiText.WikiTextTableParser.ParseTables(List`1 cleanedTables) in C:\Users\Agmas\source\repos\anno-designer\FandomParser\FandomParser\WikiText\WikiTextTableParser.cs:line 198
   at FandomParser.WikiText.WikiTextTableParser.GetTables(String wikiText) in C:\Users\Agmas\source\repos\anno-designer\FandomParser\FandomParser\WikiText\WikiTextTableParser.cs:line 17
   at FandomParser.Program.<Main>d__27.MoveNext() in C:\Users\Agmas\source\repos\anno-designer\FandomParser\FandomParser\Program.cs:line 74
```

Looks like it could be something thats been added to the wiki page that isn't being handled correctly by the parser.

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR fixes #182 and updates the presets used by the `FandomTemplateExporter`.

It also adds support for:
- new infoboxes used by the wiki
- new region "The Arctic"
- parsing unknown values (e.g. "? Credits")
- infoboxes containing references to other templates ("{{Goodsicon")

Also the `FandomTemplateExporter` has support for new workforce tiers (e.g. "Explorers").

What is missing:
- support for pages with multiple ~infoboxes~ templates of infoboxes (currently only "Roads")
- check for missing entries in `FandomTemplateExporter`
- more tests

### CODE REVIEW

**Comment by StingMcRay** [comment]
The following Buildings has also double info boxes, as it comes to Old World, New World (and or Arctic)
https://anno1800.fandom.com/wiki/Trade_Union
https://anno1800.fandom.com/wiki/Town_Hall
https://anno1800.fandom.com/wiki/Sawmill
(maybe some more buildings, but i do not know them all :) )
Do not know if that is checked for the 
> support for pages with multiple infoboxes (currently only "Roads")

**Comment by FroggieFrog** [comment]
Those pages do not contain multiple infoboxes. There are specific templates for infoboxes with multiple regions. Those templates are now supported.
What is missing is if a page contains multiple templates. (I adjusted the text)

File: FandomParser/FandomParser/WikiBuildingInfoProvider.cs [hunk 1]
```diff
@@ -65,17 +67,15 @@ private static WikiBuildingInfo ParseWikiBuildingInfo(WikiTextTableEntry table)
...
-
-                    }
 
-                    if (!int.TryParse(splittedSize[1], out int y))
+                    var couldParseX = int.TryParse(splittedSize[0], out int x);
+                    var couldParseY = int.TryParse(splittedSize[1], out int y);
+                    if (!couldParseX || !couldParseY)
                     {
-
+                        logger.Warn($"could not parse Size for \"{result.Name} ({result.Region})\": \"{table.Size}\"");
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiBuildingInfoProvider.cs:75]: Minor thing - you could use 2 double quotes `""` with `@` to escape the quotes in the string. e.g
`$@"could not parse Size for ""{result.Name} ({result.Region})"": ""{table.Size}""");`

File: FandomParser/FandomParser/WikiBuildingInfoProvider.cs [hunk 2]
```diff
@@ -149,13 +149,13 @@ private static ConstructionInfo ParseContainingInfoIcon(string constructionCost)
         {
             ConstructionInfo result = null;
 
-            if (!double.TryParse(constructionCost.Split(new[] { "{{" }, StringSplitOptions.RemoveEmptyEntries)[0], out double value))
-            {
+            var splittedInfo = constructionCost.Split(new[] { "{{" }, StringSplitOptions.RemoveEmptyEntries);
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiBuildingInfoProvider.cs:152]: Maybe a constant should be defined for `{{`?

File: FandomParser/FandomParser/WikiText/WikiTextTableEntryComparer.cs [hunk 3]
```diff
@@ -41,7 +41,7 @@ public int GetHashCode(WikiTextTableEntry obj)
             unchecked
             {
                 //name cannot be null
-                //var hashCode = obj.Name != null ? StringComparer.OrdinalIgnoreCase.GetHashCode(Name) : 0;
+                //var hashCode = obj.Name != null ? StringComparer.OrdinalIgnoreCase.GetHashCode(obj.Name) : 0;
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiText/WikiTextTableEntryComparer.cs:44]: I would remove this leftover code.

File: FandomParser/FandomParser/WikiText/WikiTextTableParser.cs [hunk 4]
```diff
@@ -11,6 +12,9 @@ public class WikiTextTableParser
     {
         private static Dictionary<WorldRegion, Dictionary<string, string>> RegionTables { get; set; }
 
+        private static readonly Regex regexNormalizeLineEndings = new Regex(@"\r\n|\n|\r", RegexOptions.Compiled | RegexOptions.IgnoreCase);
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiText/WikiTextTableParser.cs:15]: This regex does not normalize strings, it matches line endings. Should probably be renamed.

File: FandomParser/FandomParser/WikiText/WikiTextTableParser.cs [hunk 5]
```diff
@@ -112,7 +120,9 @@ private static WorldRegion ParseWorldRegion(string worldRegionHeader)
             foreach (var curTable in tables)
             {
                 var splitted = curTable.Split(new string[] { " ===" }, StringSplitOptions.RemoveEmptyEntries);
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiText/WikiTextTableParser.cs:122]: Maybe a constant should be defined for this bit of wiki syntax?

File: FandomParser/FandomParser/WikiText/WikiTextTableParser.cs [hunk 6]
```diff
@@ -169,7 +183,7 @@ private static List<string> RemoveTableHeaders(List<string> tablesWithLineBreaks
 
             foreach (var curTable in tablesWithLineBreaks)
             {
-                var split = curTable.Split(new[] { $"|Size{Environment.NewLine}" }, StringSplitOptions.RemoveEmptyEntries);
+                var split = curTable.Split(new[] { $"! style=\"text-align:center;\" |Size" }, StringSplitOptions.RemoveEmptyEntries);
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiText/WikiTextTableParser.cs:186]: Doesn't require `$` here as we are not interpolating anything.

File: FandomParser/FandomParser/WikiText/WikiTextTableParser.cs [hunk 7]
```diff
@@ -210,18 +224,47 @@ private static List<WikiTextTableEntry> ParseTableEntry(string curTable)
...
+                }
+
+                //line is empty
+                if (string.IsNullOrWhiteSpace(curLine))
+                {
+                    continue;
+                }
+
+                //line has no useful information
+                if (curLine.Equals("| style=\"text-align:center;\" |", StringComparison.OrdinalIgnoreCase) &&
```
Comment (AgmasGold) [inline FandomParser/FandomParser/WikiText/WikiTextTableParser.cs:252]: Maybe a constant should be defined for this bit of wiki syntax `|`?

File: FandomParser/InfoboxParser/InfoboxExtractor.cs [hunk 8]
```diff
@@ -0,0 +1,151 @@
...
+using System.Text;
+using System.Text.RegularExpressions;
+using FandomParser.Core;
+using InfoboxParser.Models;
+
+namespace InfoboxParser
+{
+    public class InfoboxExtractor : IInfoboxExtractor
+    {
+        private static readonly Regex regexReplaceEmpyLines = new Regex(@"^\s*$\n|\r", RegexOptions.Multiline | RegexOptions.Compiled);
```
Comment (AgmasGold) [inline FandomParser/InfoboxParser/InfoboxExtractor.cs:13]: This regex matches empty lines, it does not replace them - could probably do with being renamed.

File: FandomParser/Tests/FandomParser.Tests/Properties/AssemblyInfo.cs [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+using System.Runtime.CompilerServices;
+using System.Runtime.InteropServices;
+
+// General Information about an assembly is controlled through the following
+// set of attributes. Change these attribute values to modify the information
+// associated with an assembly.
+[assembly: AssemblyTitle("FandomParser.Tests")]
+[assembly: AssemblyDescription("")]
+[assembly: AssemblyConfiguration("")]
+[assembly: AssemblyCompany("Hewlett-Packard")]
```
Comment (AgmasGold) [inline FandomParser/Tests/FandomParser.Tests/Properties/AssemblyInfo.cs:11]: Might want to change this :)

File: FandomParser/Tests/InfoboxParser.Tests/InfoboxParser.Tests.csproj [hunk 10]
```diff
@@ -50,6 +50,42 @@
     <None Update="Testdata\empty_BothWorlds.infobox">
       <CopyToOutputDirectory>Always</CopyToOutputDirectory>
     </None>
+    <None Update="Testdata\Extractor\input_Bakery.txt">
```
Comment (AgmasGold) [inline FandomParser/Tests/InfoboxParser.Tests/InfoboxParser.Tests.csproj:53]: As these are all the same, and we are using the new format, we can use 
```xml
<None Update="Testdata\**\*.txt">
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
<None Update="Testdata\**\*.infobox">
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```
or possibly just the following, although this is not tested
```xml
<None Update="Testdata\**\*.txt, Testdata\**\*.infobox">
     <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
</None>
```

and remove all the individual entries.

File: FandomParser/FandomParser/WikiBuildingInfoProvider.cs (hunk 2 above)
Comment (FroggieFrog) [reply FandomParser/FandomParser/WikiBuildingInfoProvider.cs:152]: Shouldn't make mauch of a difference because the compiler will make it a contant anyway, but I changed it.

File: FandomParser/FandomParser/WikiBuildingInfoProvider.cs (hunk 1 above)
Comment (FroggieFrog) [reply FandomParser/FandomParser/WikiBuildingInfoProvider.cs:75]: The current style matches the rest of the whole repo and I think this is more common in general.
