### PR TITLE
Properly support prereleases (fixes #228)

### LINKED ISSUE #228: AutoUpdate: wrong result when support for Pre-Release is active
If the support for pre-releases active, the `UpdateHelper` only finds pre-releases, regardless if they are older than a new not-pre-release.

The Helper should check for both, latest release and latest pre-release and compare their versions.

### PR DESCRIPTION
**Pull request by FroggieFrog**
This PR fixes #228.
Also some log entries have beeen added and adjusted.

### CODE REVIEW

File: AnnoDesigner/UpdateHelper.cs [hunk 1]
```diff
@@ -335,32 +335,71 @@ private AvailableRelease CheckForAvailableRelease(ReleaseType releaseType)
...
+
+            return result;
+        }
+
+        private Version ParseVersionFromTag(Release release, string tagToCheck)
+        {
+            var result = default(Version);
+
+            var versionString = release.TagName.Replace(tagToCheck, string.Empty).Trim();
+            if (!Version.TryParse(versionString, out var parsedVersion))
```
Comment (AgmasGold) [inline AnnoDesigner/UpdateHelper.cs:396]: Why don't we just use `result` here, rather than assigning a new variable? `default(Version)` will be `null`, which means we can just return `result` at the end of the method, and remove the `result = parsedVersion` line.

In fact - we could just get rid of `var result = default(Version)`  entirely, assuming `TryParse` does not set the out variable to an empty instance or something else other than `null`.

Comment (FroggieFrog) [reply AnnoDesigner/UpdateHelper.cs:396]: As a matter of fact exactly this was my thought behind using a separate variable.
I don't know the inner of TryParse so I tried to make it explicit. Who cares about that extra bytes? It also is no critical path so there also is no GC pressure.
